### ISSUE TITLE
Bug with controls for detector in Phoenix menu

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#127]
When I click on the 'gear' next to the detector, multiple wireframe opacity controls appear

Also, it would be good to have the scale show the current value ... otherwise it's very hard to get back to where we are (actually I think the scale should not been shown outside of playground)

**Comment by EdwardMoyse** [comment]
![Aug-25-2020 16-01-47](https://user-images.githubusercontent.com/6764617/91184653-2a53e400-e6ed-11ea-9cfd-3df87d93cbd5.gif)

**Comment by 9inpachi** [comment]
Good find!
I didn't notice this - since I don't often open this setting - or may be I have been debugging with CMS more where it doesn't happen.
I am including the fix in the next PR for animations.

**Comment by 9inpachi** [comment]
Also, should I add the editable value option for "Opacity" as well?
I will remove the scale option. I am not sure if we will be able to make it optional for playground only since everything happens inside the UI service. And I am not sure if we should add a parameter for it in the geometry loading functions of event display. We already have [five parameters](https://github.com/HSF/phoenix/blob/master/src/app/services/eventdisplay.service.ts#L148-L149).

**Comment by EdwardMoyse** [comment]
I think opacity is useful, but I can't imagine why anyone would want to change the scale of part of an actual experiment.

I was more imagining that this would be in [configuration](https://github.com/HSF/phoenix/blob/master/src/app/services/extras/configuration.model.ts).

**Comment by 9inpachi** [comment]
I see. I didn't focus much on the configuration since it didn't offer much to begin with.
I think we can introduce a couple of other options for the Phoenix menu through configuration as well. But probably not possible right away.
