### ISSUE TITLE
Add functionality so that Phoenix can be started up with a specific event

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#149]
The ATLAS usecase is this - physics analysis might want to have a dedicated webpage which shows 'their' event, so they can use it as part of their analysis presentation. Ideally they can also configure the setup of Phoenix to show just the objects they care about (the recent PR #148 should really help with this!)

I'm thinking that the easiest/quickest might be to have a variant of `npm run release` which takes as an argument a JiveXML file and a configuration file, and then creates an instance with this file embedded in the html. And then this can just be copied to a server.

Ideally (but this much less important) it would only contain the atlas section (this should be configurable, so other experiments can use it too)

But there may well be a better solution!

**Comment by 9inpachi** [comment]
Since it's a minimal and unique use case. I think the ideal way of doing this would be to create a separate application which uses the `phoenix-event-display` and `phoenix-app` packages to have only a single page (like the ATLAS experiment) to load a specific event with UI and Phoenix menu controls.

If we want to use the `phoenix-app` without creating a new one, I don't know if it's even possible to deploy a single part / page of the application.

**Comment by EdwardMoyse** [comment]
This sounds perfect - I just don't want to avoid duplicated code. But if we can use `phoenix-app`, this should be minimal

**Comment by 9inpachi** [comment]
I was trying to do this today and it seems there is no easy way around using the components from `phoenix-app` in a different app. What would make sense is that we make a library and add the components we have to the library. We might be able to make the library a part of the `phoenix-app` itself (or a different package).

**Comment by EdwardMoyse** [comment]
Okay, understood. This is definitely better than just copying code. I don't have any strong opinions about whether it's best to be part of `phoenix-app` or a new (`phoenix-ui`?) library...
