### ISSUE TITLE
Phoenix isn't working with Oculus browser or Firefox reality on Quest2

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#150]
We don't see the VR button. First issue is to work out how to debug this, but opening this to remind me.

**Comment by 9inpachi** [comment]
Can you check if the official three.js example for VR works? (https://threejs.org/examples/webxr_vr_cubes.html)

**Comment by EdwardMoyse** [comment]
Yes it does. I’ll try to connect it to a PC tomorrow and enable remote
debugging.

**Comment by 9inpachi** [comment]
Oh yes, one more important thing. Are you running the app with HTTPS?

It's really peculiar if it still doesn't work. Because we have the same check as the three.js VRButton. ([OUR CODE](https://github.com/HSF/phoenix/blob/master/packages/phoenix-app/src/app/components/ui-menu/vr-toggle/vr-toggle.component.ts#L17-L24) - [THEIR CODE](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/webxr/VRButton.js#L124-L139))

**Comment by EdwardMoyse** [comment]
Doh. Sorry, yes, that was it.
