### ISSUE TITLE
Objects loaded with the "Load scene" button are not added as "geometries"

### ISSUE THREAD

**Issue by ric-bianchi** [HSF/phoenix#25]
When loading a scene with the "Load scene" button, the objects loaded are not added to the `Geometry` tab. 

Ideally, a new entity in the Geometry tab should be created, with a linked "Show" button to switch that ON and OFF.

Also, clicking on volumes loaded as a "scene file" does not trigger any information in the "volume information" overlay.

**Comment by EdwardMoyse** [comment]
Yes, this is because this is basically done by threejs. It will be a bit more complicated to do ourselves - Emilio and I discussed it and it will require inventing our own format. One solution might be to have a json dictionary of the paths to the various objects loaded. Obviously this makes it a quite fragile though, but it does also keep it compact.
