### ISSUE TITLE
When loading a new event, the event display configuration should not reset to everything

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#261]
I just tried loading a new XML file, and the configuration of what is displayed seems to reset to everything on.

Phoenix should keep the existing configuration.

**Comment by 9inpachi** [comment]
This isn't a bug though, it's expected. When we load a new event, the entire Phoenix menu configuration is reconstructed for that particular event because each event has different kind of objects and collections.

Personally, I am not sure if not resetting the configuration should be the intended behavior. The event data is deeply bound with the Phoenix menu configuration. Each event has different kind of objects and may or may not contain some object type so this will assume that the newly loaded event data is similar and contains the same type of data/objects that can overlap the currently loaded event. I would give this a -1 because of anti-intuitive behavior in my opinion. We can discuss this in our weekly meeting.
