### ISSUE TITLE
Add more unit tests to improve coverage

### ISSUE THREAD

**Issue by emiliocortina** [HSF/phoenix#27]
Code coverage is currently at only 50%: https://coveralls.io/github/HSF/phoenix?branch=master

**Comment by EdwardMoyse** [comment]
93% now!

**Comment by 9inpachi** [comment]
@EdwardMoyse This coverage is for the Angular application only.

I did increase the overall coverage to 89% when both the event display and the app were together but now the tests for event display are deprecated since the event display and the other parts are not Angular services anymore. They need to be set up from ground up using some framework (may be jasmine).

Most of the tests should be reusable with some tweaks since they were written to be generic and independent.

**Comment by EdwardMoyse** [comment]
Oh of course... I didn't think to check the framework.
