### ISSUE TITLE
Selecting hits shows a list of objects

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#278]
Of course the reason is clear - hits are different from other event data. But would be better to see if there is something more useful we can do (or print a message explaining that selecting hits isn't supported if we really can't handle this)

![image](https://user-images.githubusercontent.com/6764617/115138653-b5436f00-a02d-11eb-8b9b-a70a2af918e3.png)

**Comment by 9inpachi** [comment]
@EdwardMoyse — I was trying to fix this. The fix works but I realized that a lot of UI integration broke because of "concatenate objects" essentially because of not using collections as arrays but as parameters for objects.

Does it make sense to handle these objects differently, may be for hits we could move the entire collection (concatenate object) to the first index of the collection array so it still holds up with the UI integration?
