### ISSUE TITLE
Fix warnings when exporting threjs scene

### ISSUE THREAD

**Issue by emiliocortina** [HSF/phoenix#28]
Currently when exporting the scene in the Playground section many warning messages appear on the console.
This seems to be the cause that OBJ objects exported with our application appear very dark when they are loaded back again.

**Comment by ss4774** [comment]
I fixed some issues but this seems like a limitation of the current GLTF exporter (Phong materials will get changed to Standard materials. These will appear darker due to default Standard material parameters).

**Comment by emiliocortina** [comment]
@ss4774 Turns out that it wasn't the materials that made the objects darker, but the lights. For some reason the exporter doesn't support some lights that we use and when loading the scene they were missing.
I found a workaround to this some time ago by adding a call to 'this.setLights()' after loading the imported scene.

<img width="513" alt="Captura de pantalla 2019-08-16 a las 11 08 13" src="https://user-images.githubusercontent.com/43990884/63157041-5e92c000-c016-11e9-9aea-7a80ca51664e.png">

**Comment by ss4774** [comment]
@emiliocortina  I am quite confident that materials are the culprit to this issue. I found this inside of GLTF implementation and discovered that corresponding warning from browser are connected with material definitions. However, as you said it is also true that some light are not supported and not exported. Such as ambient light, which does contribute a fair part to the overall brightness.

I did notice the call to to "this.setLights()", but I found an issue with this that every time I would load a scene, there would be too many lights (from export and newly added ones). Regardless of adding a new set of lights, the objects would get either too bright (because there was too many light) or too dark. Also there was a problem with exporting an axis object due to GLTF material conversion.
My solution was to export only an event specific object so I created an exclusion list. This way I was able to export only necessary objects and keep lights at correct configuration.

I posted a pull request along with some other fixes, so you can take a look.
