### ISSUE TITLE
Selecting items on exported scene

### ISSUE THREAD

**Issue by emiliocortina** [HSF/phoenix#29]
Info about items is not displayed when clicking after loading them from a previously exported scene.

**Comment by ss4774** [comment]
I took a look at this problem. I will post a fix after I do some rework on a loader.

**Comment by emiliocortina** [comment]
Sorry Sebastien I didn't close this issue before.
Turns out I had already debugged the problem and identified where it came from but didn't fix it for some reason.
The cause of this is that when loading the scene the array of objects 'this.objects' that we pass to the ray caster for intercepting was empty so it didn't find any object to intersect.
<img width="600" alt="Captura de pantalla 2019-08-16 a las 10 57 52" src="https://user-images.githubusercontent.com/43990884/63156504-17f09600-c015-11e9-9600-f1ab4caf75b3.png">

**Comment by emiliocortina** [comment]
Changing it to 'this.scene.children' I think it's better as we don't rely on other variables, just on the visible  objects of the scene.

<img width="600" alt="Captura de pantalla 2019-08-16 a las 10 57 04" src="https://user-images.githubusercontent.com/43990884/63156674-7a499680-c015-11e9-852d-941d260d6b7a.png">

Thank you for your help by the way, if you don't mind I will upload the fix and close this issue.

**Comment by ss4774** [comment]
@emiliocortina No problem. Yes, the problem was an empty scene object inside of objects array, so there was nothing to intersect. You found quite an elegant solution.
I solved this by keeping the objects array, so that intersection is only applied on event data. I tried to avoid computation on a whole scene. 

At the same time I was going through loader and I found out that you finished with muons as well.
I found some other potential bugs and tried to fix them.
