### ISSUE TITLE
Phoenix menu does not have a scroll bar

### ISSUE THREAD

**Issue by smitadarmora** [HSF/phoenix#317]
For the Phoenix menu, there is no scroll bar. As a result, different menu options and event display can not be viewed simultaneously.

**Comment by 9inpachi** [comment]
I have tried to solve this multiple times but the issue is this: https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue

Since the configuration options appear outside (to the left of) the main body, using overflow scroll hides them because of the limitation above. We could move the configuration options to show on top of the main body and it should work but not sure how good that is in terms of UI/UX. Alternatively we could abandon absolute positioning and have the Phoenix menu stick to the right side of the screen at all times like iSpy. Any preferences or thoughts @EdwardMoyse?
