### ISSUE TITLE
Adapt the API docs generation script

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#375]
Since compodoc is updated now, the way the title of API docs is handled is different. Instead of showing the title at the top left of the API docs page, there is a compodoc logo. We should update the Node.js script [gen-api-docs.js](https://github.com/HSF/phoenix/blob/master/packages/phoenix-event-display/scripts/gen-api-docs.js) to remove the code that did the replacement of the text at the top left with the Phoenix logo or adapt it to replace the compodoc logo with the Phoenix logo.

![image](https://user-images.githubusercontent.com/36920441/142660165-b8c4b2c6-ca8e-4c24-b640-2cc8fe56b15f.png)

**Comment by subho951m** [comment]
Sir I think this issue has already been resolved.
Are you talking about the documentation?
![Screenshot (1247)](https://user-images.githubusercontent.com/88569334/143397999-2b0b4687-b4c7-4851-8253-996146622fa9.png)
.

**Comment by 9inpachi** [comment]
Hey @subho951m,

Good point. So I checked it again and this only happens in the dark theme. If you change your browser's theme to dark and compodoc picks up the settings, it uses the invert compodoc logo which is a different image from what we replace using the [gen-api-docs.js](https://github.com/HSF/phoenix/blob/master/packages/phoenix-event-display/scripts/gen-api-docs.js) script.

**Comment by subho951m** [comment]
@9inpachi Ok sir I will try to solve this problem. Is this issue still opened or have you solved it?

**Comment by 9inpachi** [comment]
@subho951m It's still open.

**Comment by subho951m** [comment]
@9inpachi  sir in my android phone if I choose dark mode + desktop site, I can see that this problem is arising. 
But on other hand in my pc (windows 10) chrome if I choose "auto dark mode for web content" , the problem is not arising. I am not sure what setting is different in my android mobile and this PC. Can you please help
![android chrome](https://user-images.githubusercontent.com/88569334/143458987-a6f8aef0-f992-4866-bf9f-6e474ba3b319.jpg)
?
this is my android chrome rendering
![PC Chrome](https://user-images.githubusercontent.com/88569334/143459155-baa8625c-1f27-463a-b219-f82aad9ffe57.png)
this is my chrome rendering
![Chrome settings](https://user-images.githubusercontent.com/88569334/143459315-feeb3255-2232-4b6c-93b7-0cd32f62c31e.png)
this is my chrome setting for dark mode.
can you please help what setting should I do in PC so that it matches the android.

**Comment by 9inpachi** [comment]
The experimental settings you enabled are different than dark mode. The latest chrome I think is able to pick up the theme based on your Windows preferences. So if you have dark theme enabled on Windows, Chrome should also have it enabled. Otherwise you can try installing this theme https://chrome.google.com/webstore/detail/dark-theme-for-google-chr/annfbnbieaamhaimclajlajpijgkdblo?hl=en.

Apart from this, you should probably look up how getting the dark theme preferences work in JavaScript.

Sometimes, websites also store the theme preferences (as Phoenix does) on your first load and then even if you change the theme of the browser, the preference in the local storage prevails. You can check the local session storage in browser console to see if any option like that is set.

**Comment by MASTERAMARJEET** [comment]
Is this issue open? Can I give it a try?

**Comment by MASTERAMARJEET** [comment]
Hello,
Thanks @9inpachi. I have created to PR with a possible fix. Kindly have a look.
