### ISSUE TITLE
Close sections created by clipping

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#39]
Currently the clipping planes don't look too nice since the volumes are left open. However it looks like there are some simple hacks/workarounds which might work:

https://jsfiddle.net/wilt/qo869tb3/

**Comment by 9inpachi** [comment]
Hi @EdwardMoyse 

This SectionHelper doesn't seem really helpful in Phoenix's usecase.
We have to add it for each geometry we insert into the scene and the result is somewhat odd.

Here is how it looks after porting https://rawgit.com/Wilt/three.js/dev-sectionhelper/src/extras/helpers/SectionHelper.js to typescript.

![image](https://user-images.githubusercontent.com/36920441/78362495-aa10d300-75d3-11ea-8e59-2f5e529432a9.png)

**Comment by EdwardMoyse** [comment]
Ah, no, that doesn't look very good does it? Hmm. That's a shame. :-(
Thanks for investigating - time to have a rethink.

**Comment by 9inpachi** [comment]
https://stackoverflow.com/questions/37090942/how-to-render-clipped-surfaces-as-solid-objects

This looks like a more global fix to me. WDYT?
It's also possible to create a new derived material for detector geometries and then use an edited shader for it. It's a sideways approach but should work.

**Comment by EdwardMoyse** [comment]
Isn't that just what you just tried? (It's exactly that stackoverflow question which led me to the SectionHelper)

**Comment by 9inpachi** [comment]
`SectionHelper` was mentioned in the second answer. (the one we tried)
The first talks about editing the shaders of materials.

**Comment by EdwardMoyse** [comment]
Ah - right. Worth a try I guess!

**Comment by 9inpachi** [comment]
Hi Edward,

Sorry for the late followup. I initially tried editing the file `/src/renderers/shaders/ShaderLib/meshphong_frag.glsl` as mentioned in the issue but it doesn't work.
I just got back to this issue and after a lot of looking around in the files I found that three.js files have these shaders declared inline. `three.module.js` in our case.

Here is the result:
![image](https://user-images.githubusercontent.com/36920441/80044193-2d5f7d80-851d-11ea-99c2-28919469c873.png)
![image](https://user-images.githubusercontent.com/36920441/80044375-b8407800-851d-11ea-91f7-689929d92aca.png)

Now this will require editing the library files so I am not sure how it will be accommodated since we get the three module through npm.
Let me know what you think about the result then we will move on.

**Comment by EdwardMoyse** [comment]
Wow. That looks excellent! If we can possibly get that in, I think it would
be great!

**Comment by 9inpachi** [comment]
We can edit the file `node_modules/three/build/three.module.js` and not ignore it in `.gitignore`
BUT
I think it's not practical to edit the core files of the three library. Primary reason being having to edit the file for each threejs update.

I will try creating a custom object or material derived from the already available ones with a custom `fragShader`. I will give it a try as soon as I get the time (busy with FYP these days :) also have to try a custom object for tracks with `sizeAttenuation` support for #73).
