### ISSUE TITLE
Menu issues if subitems have identical names

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix#426]
I've just found out that 2 items with same name in 2 branches of the Detector menu does not work properly.
Basically they both act on the second item.

In order to reproduce, just create 2 items in different branches but with same name :

```javascript
this.eventDisplay.loadGLTFGeometry('file1.gltf','ItemName','TopDir1',1,true);
this.eventDisplay.loadGLTFGeometry('file2.gltf', 'ItemName','TopDir2',1,true);
```

**Comment by EdwardMoyse** [comment]
Yeah, I saw this too and (to my shame) did a horrible hack:
```code
      if (trackCollectionName === 'Tracks') {
```

@9inpachi maybe we can chat about this?

**Comment by 9inpachi** [comment]
> @9inpachi maybe we can chat about this?

Sure.

**Comment by 9inpachi** [comment]
From what I tried today, what you said is completely correct. We need to make changes to all those functions you mentioned.

It involves changing a lot of code and tests. What I am personally uncomfortable with is introducing new parameters to all our functions. This isn't a scalable solution and makes the code a mess.

One solution I have in mind is to change the name to include a number if the name is repeated among geometries. For example, if `Muon Barrel` was the name given to two geometries, the first geometry will have `Muon Barrel` but the second will have `Muon Barrel 1` as the name. Is this something that's acceptable?

**Comment by EdwardMoyse** [comment]
I think the problem is worse though - look at the issue where you have a
Menu item called "Tracks" and a collection called "Tracks". We can't
control what clients of Phoenix will do and so relying on names as we do
right now is inherently fragile. Within ATLAS it's forbidden to have two
collections of the same name, but this isn't guaranteed for other
experiments. And it would be pretty reasonable that if you only have one
"CaloCluster" collection, it would be called that. So I think relying on
names as we do now is not a great idea.

**Comment by 9inpachi** [comment]
I see. I didn't take events into account. Alright, that for me at least confirms that we shouldn't be using a workaround to solve this.
