### ISSUE TITLE
CI not working?

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#528]
It seems to fail with:

```
 Warning: Unexpected input(s) 'repository', 'ref', 'environment', 'required_contexts', 'auto_merge', valid inputs are ['route', 'mediaType']
Run octokit/request-action@v2.x
  with:
    route: POST /repos/{repository}/deployments
    repository: HSF/phoenix
    ref: refs/heads/dependabot/npm_and_yarn/decode-uri-component-0.2.2
    environment: pull-request
    required_contexts: []
    auto_merge: false
    mediaType: {}
  env:
    GITHUB_TOKEN: ***
POST /repos/{repository}/deployments
> repository: HSF/phoenix
> ref: refs/heads/dependabot/npm_and_yarn/decode-uri-component-0.2.2
> environment: pull-request
> required_contexts: 
> auto_merge: false
> mediaType: [object Object]
< 403 304ms
Error: Resource not accessible by integration
```

**Comment by 9inpachi** [comment]
We have been getting warnings for a long time. I think we need to update the GitHub action we are using to create the deployment.

**Comment by 9inpachi** [comment]
We don't need to change anything here. The warnings in the action are expected since some changes in the GitHub Actions runner. There is an open issue in the action's repo (https://github.com/octokit/request-action/issues/26#issuecomment-634167909).

The error I think was happening because the dependency bot with its GitHub token doesn't have permissions to send a request to GitHub API to create a deployment.

**Comment by EdwardMoyse** [comment]
Thanks!
