### ISSUE TITLE
No exporter for actual experiments?

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#54]
Hi,

On the deployed website, I notice that exporters are not there for actual experiments. Are there any errors with this? They exist for the playgrounds.
We could implement a `.gltf` exporter which makes it easier to export the whole scene through `three.js`.

**Comment by EdwardMoyse** [comment]
We could. Honestly I hadn't imagined that we would want to do this because this "freezes" the displays... IIRC loading a scene gltf doesn't rebuild the menus, for example.

**Comment by emiliocortina** [comment]
Hi!,
The exporters work in any section.
They are only in the playground because that section was intended to showcase all the available functionality of the application, but they can as well be added to any other experiment.
I am currently working on refactoring the UI to a separate component so soon it will all be uniform across the different sections.
