### ISSUE TITLE
Expanding some event data menu items is VERY slow

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#566]
For example, with:
https://phoenixatlas.web.cern.ch/PhoenixATLAS/?file=data%2FBriefings%2FJiveXML_304008_1533145462.xml&type=jivexml

Go to the Phoenix Menu -> Event Data -> Tracks -> Tracks_ and click on the gear. 

It took > 30s for me.

**Comment by EdwardMoyse** [comment]
Update: and the particular event I'm looking at today, it's impossible to change the colour of the tracks on Safari:
![image](https://user-images.githubusercontent.com/6764617/227948497-fc81dac1-ab95-4c1b-9e33-74f5ba23d7c9.png)
:-(

**Comment by EdwardMoyse** [comment]
Update: and the particular event I'm looking at today, it's impossible to change the colour of the tracks on Safari:
![image](https://user-images.githubusercontent.com/6764617/227948497-fc81dac1-ab95-4c1b-9e33-74f5ba23d7c9.png)
:-(

**Comment by EdwardMoyse** [comment]
Actually, even opening the `Tracks` menu is very slow ... unfortunately it's hard to debug on this computer, probably because it's running out of memory, and Chrome keeps telling me 'Aw snap!'

**Comment by EdwardMoyse** [comment]
Actually, even opening the `Tracks` menu is very slow (the screenshot below is a profile doing only that - I have not opened `Tracks_`) Unfortunately it's hard to debug on this computer, probably because it's running out of memory, and Chrome keeps telling me 'Aw snap!'

![image](https://user-images.githubusercontent.com/6764617/227975894-a0eb4b61-965e-45b7-8683-37d2031304e9.png)

**Comment by 9inpachi** [comment]
It's because of the combination of `ngx-slider` and `ngSwitchCase` we use. Both of them are memory intensive. I tried some stuff and removing `ngx-slider` seems to fix the issue.

We either should implement our own range slider or remove it entirely and use inputs for cuts.

**Comment by EdwardMoyse** [comment]
> It's because of the combination of `ngx-slider` and `ngSwitchCase` we use. Both of them are memory intensive. I tried some stuff and removing `ngx-slider` seems to fix the issue.
> 
> We either should implement our own range slider or remove it entirely and use inputs for cuts.
> 
> [angular-slider/ngx-slider#45](https://github.com/angular-slider/ngx-slider/issues/45)

Wow @9inpachi - you *have* to tell me how you debugged this when we next chat!

Does this really explain how the memory was climbing from ~200Mb to 3Gb? I'd be surprised (given the explanation in that link), especially since it seems to be much worse for tracks than for any other object, and the menu itself shouldn't (I think!) depend on the underlying object.

In terms of removing the slider, if we have to, we have to ... but the BIG problem I see here is this will invalid saved configuration. Since ATLAS is using Phoenix for publically available briefings, and other experiments have distributed posters with QR codes, it really isn't okay for us to completely break old configurations with new versions :-(

Did you see I have an open PR to move to a new slider fork (#553)? We could also try that (though looking at the commits I can't really see how it can help)

**Comment by EdwardMoyse** [comment]
Okay, I just checked and #572 DOES fix the memory consumption issues. :frowning: 

That's crazy!

**Comment by 9inpachi** [comment]
> Wow @9inpachi - you have to tell me how you debugged this when we next chat!

It was nothing magical and I don't usually use any debugging tools. Since I knew where the logic related to opening a menu and config existed, I knew it was related to Angular trying to render the UI for the configs. Then I just removed the template markup for all configs and tested if it fixed the memory issue — which it did. And then, through divide and conquer, I removed the code for the `rangeSlider` config only and found that it was the one config taking the most memory. It makes sense because it was the config with the most code.

I initially though that it was because of `ngSwitchCase` so I used a combination of `ng-container` (with `ngTemplateOutlet`) and `ng-template` to not use `ngSwitchCase` for loading the configs but it was pretty much the same. Then I tried using CSS (`[hidden]` Angular attribute) but it didn't make sense because we did not want to have the config rendered at all if it was not the one specified.

The reason I know `ngIf` and `ngSwitchCase` are not great for performance is because they dynamically render the template and parts of it through JavaScript logic which is not as simple as hiding things with CSS since it involves adding and removing nodes in the DOM through code compared to always having the nodes in the DOM and just hiding them through CSS. I think `ngx-slider` consumes a lot of memory during the component initialization because of all the features it has.

I think there is still a lot room for improvement in how the Phoenix menu UI is rendered.

> In terms of removing the slider, if we have to, we have to ... but the BIG problem I see here is this will invalid saved configuration. Since ATLAS is using Phoenix for publically available briefings, and other experiments have distributed posters with QR codes, it really isn't okay for us to completely break old configurations with new versions :-(
Edit: Ah, actually, if the inputs stay, maybe it still works? I guess we can test.

The state saving and loading logic exists in `phoenix-event-display` and not `phoenix-ui-components`. What it means is that the state manager saves and loads the state of `PhoenixMenuNode` and it has nothing to do with the UI. The UI is just used to make changes to the config values. The actual values are not taken from or stored in the UI but in the `configs` member of `PhoenixMenuNode`.

This design is actually very efficient in the sense that we can use other frameworks like React and have the same logic for saving and loading state with the logic being completely decoupled from the UI.

If there's a bug in saving and loading of state, then it exists in either `PhoenixMenuNode` or `StateManager`.
