### ISSUE TITLE
Connect collections information and 3D view

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#93]
If you click on a cluster, track etc, and the collections view is open, that object should be highlighted there. And vice versa. 

It would also be great to have an option (in the collections panel?) to zoom to that object.

**Comment by 9inpachi** [comment]
I don't think we have a unique identifier for each event item (cluster, track etc). We need something like that in the `userData` to identify a certain event item so we can pick it up from the collections info.

**Comment by 9inpachi** [comment]
Was finally able to make it work, only for tracks for now (could make it work with the other objects the same way). Since I mentioned we needed some kind of ID to identify the event object by, for now, I am attaching it to the tracks manually like this:
```js
const splineObject = new THREE.Line(geometry, material);
splineObject.userData = trackParams;
* splineObject.userData.item_id = Math.floor(Math.random() * 100).toString() + Date.now();
splineObject.name = 'Track';
```
I think something like this is safe enough for us.

Have a look:
![wip-collections-track-selection](https://user-images.githubusercontent.com/36920441/84191593-23381500-aab2-11ea-8cf9-fb50793d0f83.gif)

WDYT @EdwardMoyse @emiliocortina ?

**Comment by EdwardMoyse** [comment]
Making a unique id like this should be fine I think - elsewhere we have used the index of the object (e.g. track) in its collection, but perhaps this isn't so convenient here?

It looks very nice! Would it work both ways? i.e. if I clicked on a track in the collection list, would it be highlighted in 3D?

**Comment by 9inpachi** [comment]
> Making a unique id like this should be fine I think - elsewhere we have used the index of the object (e.g. track) in its collection, but perhaps this isn't so convenient here?

Do you mean the uuid by index? If so, then yes. It might be more convenient. I was testing things with the current implementation.

> It looks very nice! Would it work both ways? i.e. if I clicked on a track in the collection list, would it be highlighted in 3D?

I haven't done that yet. But making it work the other way around will be much simpler, however I am not sure how we can highlight the tracks since that doesn't work right now (because of the `Line` geometry. I will look into what I can do.

**Comment by EdwardMoyse** [comment]
> Do you mean the uuid by index? If so, then yes. It might be more convenient. I was testing things with the current implementation.

Yes. This shoudl be generally safe I think - in fact, this is what we do in ATLAS with our general reconstruction software ... links between objects are ("Collection name" : index )

Of course you're right that highlighting tracks is a general issue - I guess we could change the colour of that track? But it would be best to fix it properly.

**Comment by 9inpachi** [comment]
Moving the camera to look at an object but it doesn't work for tracks and hits. So I was wondering if we should switch to outlines? Or its also possible to keep both the "Go to" and "Highlight" option from the collection panel.

![wip-collections-twoway-selection](https://user-images.githubusercontent.com/36920441/84374988-4f5dae00-abf8-11ea-9889-b60f3949db0d.gif)

**Comment by 9inpachi** [comment]
Hi,

I forgot to give an update on this. I added the option to highlight.

![wip-collections-w-highlight](https://user-images.githubusercontent.com/36920441/84650631-15571980-af22-11ea-954f-f15acda333be.gif)

The "Look at object" option doesn't work for tracks and hits. I will look into what I can do about it.
